Change mariadb use alpine.

diff --git a/build/mysql/Dockerfile b/build/mysql/Dockerfile
--- a/build/mysql/Dockerfile
+++ b/build/mysql/Dockerfile
@@ -1,12 +1,54 @@
-FROM mariadb:latest
+FROM alpine:latest
 MAINTAINER ChurchCRM
 
-RUN apt-get update \
-    && apt-get install -y jq \
-    && mkdir -p /scripts/pre-init.d/
+ENV GOSU_VERSION 1.11
+RUN set -eux; \
+	\
+	apk add --no-cache --virtual .gosu-deps \
+		dpkg \
+		gnupg \
+	; \
+	\
+	dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
+	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+	\
+# verify the signature
+	export GNUPGHOME="$(mktemp -d)"; \
+# for flaky keyservers, consider https://github.com/tianon/pgp-happy-eyeballs, ala https://github.com/docker-library/php/pull/666
+	gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+	command -v gpgconf && gpgconf --kill all || :; \
+	rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+	\
+# clean up fetch dependencies
+	apk del --no-network .gosu-deps; \
+	\
+	chmod +x /usr/local/bin/gosu; \
+# verify that the binary works
+	gosu --version; \
+	gosu nobody true
 
+RUN set -x \
+    && apk --update add --no-cache bash jq mariadb mariadb-client mariadb-server-utils pwgen tzdata socat \
+    && rm -f /var/cache/apk/*
+#COPY --from=mariadb:latest /usr/local/bin/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
+COPY ./docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
 COPY ./entrypoint.sh /scripts/entrypoint.sh
-RUN chmod +x /scripts/entrypoint.sh
-ENV TERM="xterm-color"
+RUN set -x \
+    && sed -ri 's/^user\s/#&/' /etc/my.cnf /etc/my.cnf.d/* \
+    && rm -rf /var/lib/mysql \
+	&& mkdir -p /var/lib/mysql /var/run/mysqld \
+	&& chown -R mysql:mysql /var/lib/mysql /var/run/mysqld \
+    && chmod 777 /var/run/mysqld \
+	&& echo '[mysqld]\nskip-host-cache\nskip-name-resolve' > /etc/my.cnf.d/docker.cnf \
+    && mkdir -p /scripts/pre-init.d \
+    && chmod +x /usr/local/bin/docker-entrypoint.sh \
+    && mkdir -p /docker-entrypoint-initdb.d \
+    && ln -s usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh \
+    && chmod +x /scripts/entrypoint.sh
 
+ENV TERM="xterm-color"
+EXPOSE 3306
+VOLUME ["/var/lib/mysql"]
 ENTRYPOINT ["/scripts/entrypoint.sh"]
